package com.shipeng.bit;

/*
 * Find the difference
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * 
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 * ~ -- the unary complement
 * & -- bitwise and
 * ^ -- bitwise exclusive or
 * | -- bitwise inclusive or
 * 
 */

public class FindTheDifference {

	public char findTheDifference(String s, String t) {
		char c = 0;
		for (int i = 0; i < s.length(); i++) {
		    c = (char) (c ^ s.charAt(i));
		}
		for (int j = 0; j < t.length(); j++) {
			c = (char) (c ^ t.charAt(j));
		}
		return c;
	}
	
	
}
